#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# Scripts
mkdir -p $HOME/.local/bin

ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t

echo "Is this hell?"
echo -n "y/n: "

read -r hell

if [ $hell = "y" ]; then
    ln -sf $DOTFILES/zsh/aliases/home $HOME/.aliases
    ln -sf $DOTFILES/zsh/env/home $HOME/.zshenv
else
    ln -sf $DOTFILES/zsh/aliases/work $HOME/.aliases
    ln -sf $DOTFILES/zsh/env/work $HOME/.zshenv

    ln -sf $DOTFILES/tmux/2pan $HOME/.local/bin/2pan
    ln -sf $DOTFILES/tmux/3pan $HOME/.local/bin/3pan
fi

# Zsh
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# Alacritty (switch to .toml when updated to v0.13.X)
mkdir -p $HOME/.config/alacritty
ln -sf $DOTFILES/alacritty/alacritty.yml $HOME/.config/alacritty/alacritty.yml

# Tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# Neovim
rm -rf $HOME/.config/nvim
ln -sf $DOTFILES/nvim $HOME/.config/nvim

# Git
ln -sf $DOTFILES/git/gitignore $HOME/.gitignore
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

if [ ! -f "$HOME/.gitconfig.local" ]; then
    cp $DOTFILES/git/gitconfig.local.example $HOME/.gitconfig.local
fi

# NVM (Node Version Manager)
mkdir -p $HOME/.nvm
ln -sf $DOTFILES/nvm/default-packages $HOME/.nvm/default-packages

