#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

gum confirm "Run setup for work?" && MACHINA="WORK" || MACHINA="HELL"

# Scripts
mkdir -p $HOME/.local/bin

ln -sf $DOTFILES/utils/jump $HOME/.local/bin/jump # Shortcut for SSH to server and specific dir
ln -sf $DOTFILES/utils/vsjump $HOME/.local/bin/vsjump # Shortcut for VS Code remote to server and specific dir
ln -sf $DOTFILES/utils/t $HOME/.local/bin/t

# Hyprland
mkdir -p $HOME/.config/waybar
mkdir -p $HOME/.config/rofi

ln -sf $DOTFILES/hyprland/hyprland.conf $HOME/.config/hypr/hyprland.conf
ln -sf $DOTFILES/hyprland/hyprlock.conf $HOME/.config/hypr/hyprlock.conf

ln -sf $DOTFILES/hyprland/waybar/config.jsonc $HOME/.config/waybar/config.jsonc
ln -sf $DOTFILES/hyprland/waybar/modules.json $HOME/.config/waybar/modules.json
ln -sf $DOTFILES/hyprland/waybar/mocha.css $HOME/.config/waybar/mocha.css
ln -sf $DOTFILES/hyprland/waybar/style.css $HOME/.config/waybar/style.css

ln -sf $DOTFILES/hyprland/rofi/config.rasi $HOME/.config/rofi/config.rasi
ln -sf $DOTFILES/hyprland/rofi/catppuccin-mocha.rasi $HOME/.config/rofi/catppuccin-mocha.rafi

# Ghostty
mkdir -p $HOME/.config/ghostty
ln -sf $DOTFILES/ghostty/config $HOME/.config/ghostty/config

# Tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# Neovim
rm -rf $HOME/.config/nvim
ln -sf $DOTFILES/nvim $HOME/.config/nvim

# Git
ln -sf $DOTFILES/git/gitignore $HOME/.gitignore
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

# Zsh
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# Starship
ln -sf $DOTFILES/starship/starship.toml $HOME/.config/starship.toml

if [ ! -f "$HOME/.gitconfig.local" ]; then
    gum style \
        --foreground 212 --border-foreground 212 --border double \
        --align center --width 50 --margin "1 2" --padding "2 4" \
        'Remember to update .gitconfig.local'

    cp $DOTFILES/git/gitconfig.local.example $HOME/.gitconfig.local
fi

if [ $MACHINA = "HELL" ]; then
    echo ">> Setting up symlinks for aliases and env for home"

    ln -sf $DOTFILES/zsh/aliases/home $HOME/.aliases
    ln -sf $DOTFILES/zsh/env/home $HOME/.zshenv
else
    echo ">> Setting up symlinks for aliases and env for work"

    ln -sf $DOTFILES/zsh/aliases/work $HOME/.aliases
    ln -sf $DOTFILES/zsh/env/work $HOME/.zshenv

    ln -sf $DOTFILES/tmux/2pan $HOME/.local/bin/2pan
    ln -sf $DOTFILES/tmux/2vpan $HOME/.local/bin/2vpan
fi

# NVM (Node Version Manager)
mkdir -p $HOME/.nvm
ln -sf $DOTFILES/nvm/default-packages $HOME/.nvm/default-packages

