#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
MACHINA="HELL"

read -p "Run setup for work (yN)? " yn
case $yn in
    [Yy]* ) MACHINA="WORK";;
    [Nn]* ) MACHINA="HELL";;
    * ) echo "Running default setup for $MACHINA.";;
esac

# Scripts
mkdir -p $HOME/.local/bin

ln -sf $DOTFILES/scripts/t $HOME/.local/bin/t
ln -sf $DOTFILES/scripts/jump $HOME/.local/bin/jump
ln -sf $DOTFILES/scripts/vs-jump $HOME/.local/bin/vs-jump

if [ $MACHINA = "HELL" ]; then
    echo ">> Setting up symlinks for aliases and env for home"

    ln -sf $DOTFILES/zsh/aliases/home $HOME/.aliases
    ln -sf $DOTFILES/zsh/env/home $HOME/.zshenv

    # Include if using I3WM
    # mkdir -p $HOME/.config/i3
    # ln -sf $DOTFILES/wm/i3/config $HOME/.config/i3/config

    # mkdir -p $HOME/.config/polybar
    # ln -sf $DOTFILES/wm/polybar/config.ini $HOME/.config/polybar/config.ini

    # mkdir -p $HOME/.config/rofi
    # ln -sf $DOTFILES/wm/rofi/config.rasi $HOME/.config/rofi/config.rasi
    # ln -sf $DOTFILES/wm/rofi/catppuccin-mocha.rasi $HOME/.config/rofi/catppuccin-mocha.rasi
else
    echo ">> Setting up symlinks for aliases and env for work"

    ln -sf $DOTFILES/zsh/aliases/work $HOME/.aliases
    ln -sf $DOTFILES/zsh/env/work $HOME/.zshenv

    ln -sf $DOTFILES/tmux/2pan $HOME/.local/bin/2pan
    ln -sf $DOTFILES/tmux/3pan $HOME/.local/bin/3pan
fi

# Zsh
ln -sf $DOTFILES/zsh/zshrc $HOME/.zshrc

# Starship
ln -sf $DOTFILES/starship/starship.toml $HOME/.config/starship.toml

# Alacritty (switch to .toml when updated to v0.13.X)
mkdir -p $HOME/.config/alacritty
ln -sf $DOTFILES/alacritty/alacritty.yml $HOME/.config/alacritty/alacritty.yml

# Tmux
ln -sf $DOTFILES/tmux/tmux.conf $HOME/.tmux.conf

# Neovim
rm -rf $HOME/.config/nvim
ln -sf $DOTFILES/nvim $HOME/.config/nvim

# Git
ln -sf $DOTFILES/git/gitignore $HOME/.gitignore
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig

if [ ! -f "$HOME/.gitconfig.local" ]; then
    echo "Remember to update .gitconfig.local"
    cp $DOTFILES/git/gitconfig.local.example $HOME/.gitconfig.local
fi

# NVM (Node Version Manager)
mkdir -p $HOME/.nvm
ln -sf $DOTFILES/nvm/default-packages $HOME/.nvm/default-packages

