#!/usr/bin/env bash

tmux new -A -s duo-panes -n duo-window -d

tmux send-keys -t duo-panes "clear" Enter
tmux send-keys -t duo-panes "copilot --banner" Enter

tmux split-window -h -t duo-panes
tmux send-keys -t duo-panes "clear" Enter
tmux send-keys -t duo-panes 'find . -type f -name "*.log" ! -path "./var/cache/*" -exec truncate -s 0 "$file" {} +' Enter

tmux send-keys -t duo-panes "clear" Enter
tmux send-keys -t duo-panes 'find . -type f -name "*.log" ! -path "./var/cache/*" -exec tail -f "$file" {} +' Enter

tmux switch-client -t duo-panes
