# Personal zsh config of Ash (ash@a-sh.dk)

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(
    git
)

source $ZSH/oh-my-zsh.sh

path=(
    $HOME/.local/bin
    $HOME/.config/composer/vendor/bin
    ./vendor/bin
    $path
)


export EDITOR=nvim
export GIT_EDITOR=nvim

# Aliases
alias vim=nvim
alias sail='[ -f sail ] && sh sail || sh vendor/bin/sail'

# Docker
alias dcup="docker-compose"

# Laravel
alias a='artisan'

if [[ "$DESKTOP_SESSION" -eq "pop" ]] ; then
	echo 'hej'
fi
