# Personal zsh config of Ash (ash@helash.dev)

if [ "$TMUX" = "" ]; then
    tmux new-session -A -s "go!" -c $HOME/code/;
fi

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(
    git
)

source $ZSH/oh-my-zsh.sh

path=(
    $HOME/.local/bin
    $HOME/.config/composer/vendor/bin
    ./vendor/bin
    $path
)

export EDITOR=nvim
export GIT_EDITOR=nvim
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Aliases
alias vim=nvim
alias pkey="xclip -selection clipboard ~/.ssh/id_rsa.pub"

# Docker
alias dcup="docker compose up -d"
alias dcdown="docker compose down"

source $HOME/.aliases

