# Personal zsh config of Ash (ash@a-sh.dk)

if [ "$TMUX" = "" ]; then
    tmux new -s "go!" -c $HOME/code/;
fi

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(
    git
)

source $ZSH/oh-my-zsh.sh

path=(
    $HOME/.local/bin
    $HOME/.config/composer/vendor/bin
    ./vendor/bin
    $path
)

export EDITOR=nvim
export GIT_EDITOR=nvim

# Aliases
alias vim=nvim
alias pkey="xclip -selection clipboard ~/.ssh/id_rsa.pub"

# Docker
alias dcup="docker-compose up -d"
alias dcstop="docker-compose stop"

source $HOME/.aliases
